/* Synthetic specimens. Every one of these was written for this tool —
   no real message, address or recipient appears anywhere in the file.
   Each isolates one technique so the engine can be seen catching it. */

(function (root) {
  'use strict';

  var SAMPLES = [
    {
      id: 'credential-phish',
      name: 'Credential phish',
      blurb: 'The everyday one. Four separate lies stacked in the headers.',
      teaches: 'DMARC fail · display-name spoof · lookalike domain · link mismatch',
      raw: [
        'Delivered-To: you@example.com',
        'Received: by 2002:a05:6214:1d0c:b0:6b2:8f1a:22e9 with SMTP id a12csp1837291qvd;',
        '        Thu, 17 Sep 2026 03:12:44 -0700 (PDT)',
        'Received: from mail-7f2a.top (mail-7f2a.top. [198.51.100.44])',
        '        by mx.example.com with ESMTPS id k7si2839201pfc.88.2026.09.17.03.12.43',
        '        for <you@example.com>; Thu, 17 Sep 2026 03:12:44 -0700 (PDT)',
        'Received-SPF: fail (example.com: domain of bounce@mailer-7f2a.top does not designate 198.51.100.44 as permitted sender) client-ip=198.51.100.44;',
        'Authentication-Results: mx.example.com;',
        '       dkim=none;',
        '       spf=fail (example.com: domain of bounce@mailer-7f2a.top does not designate 198.51.100.44 as permitted sender) smtp.mailfrom=bounce@mailer-7f2a.top;',
        '       dmarc=fail (p=REJECT sp=REJECT dis=NONE) header.from=paypa1.com',
        'Return-Path: <bounce@mailer-7f2a.top>',
        'From: "PayPal Service <service@paypal.com>" <alerts@paypa1.com>',
        'Reply-To: <recovery-desk@mailer-7f2a.top>',
        'To: you@example.com',
        'Subject: Your account access will be suspended within 24 hours',
        'Date: Thu, 17 Sep 2026 06:12:40 -0400',
        'Message-ID: <20260917101240.8A21C@mailer-7f2a.top>',
        'MIME-Version: 1.0',
        'Content-Type: text/html; charset=UTF-8',
        'Content-Transfer-Encoding: quoted-printable',
        '',
        '<html><body style=3D"font-family:Helvetica,Arial,sans-serif;color:#2c2e2f">',
        '<p>Dear Customer,</p>',
        '<p>We detected unusual sign-in activity on your account from a device we do =',
        'not recognise. As a precaution your account has been placed under limited a=',
        'ccess.</p>',
        '<p>To restore full access, please verify your account details immediately. =',
        'If we do not hear from you within 24 hours, your account will be permanentl=',
        'y suspended.</p>',
        '<p><a href=3D"https://www.paypal.com.account-verify.mailer-7f2a.top/login">=',
        'https://www.paypal.com/signin</a></p>',
        '<p>Alternatively you may <a href=3D"https://bit.ly/3xQ9kLmVerify">confirm y=',
        'our identity here</a>.</p>',
        '<p>If this was you, <a href=3D"https://www.paypal.com@203.0.113.77/secure/c=',
        'onfirm">no action is required</a>.</p>',
        '<p>Sincerely,<br>The PayPal Security Team</p>',
        '</body></html>'
      ].join('\n')
    },

    {
      id: 'bec',
      name: 'Business email compromise',
      blurb: 'Every authentication check passes. It is still an attack.',
      teaches: 'Reply-To divergence · pressure stack · why "SPF pass" is not "safe"',
      raw: [
        'Delivered-To: t.nguyen@westbrook-district.org',
        'Received: from mail.westbrook-district.org (mail.westbrook-district.org. [203.0.113.18])',
        '        by mx.westbrook-district.org with ESMTPS id 8fj2kd9',
        '        for <t.nguyen@westbrook-district.org>; Wed, 16 Sep 2026 08:41:02 -0400 (EDT)',
        'Authentication-Results: mx.westbrook-district.org;',
        '       dkim=pass header.d=westbrook-district.org;',
        '       spf=pass smtp.mailfrom=d.whitfield@westbrook-district.org;',
        '       dmarc=pass (p=QUARANTINE dis=NONE) header.from=westbrook-district.org',
        'DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=westbrook-district.org;',
        '        s=selector1; h=from:subject:date:to; bh=4Kq2LmA9tWc=; b=Hq9n2Lp4',
        'Return-Path: <d.whitfield@westbrook-district.org>',
        'From: "Dana Whitfield (Principal)" <d.whitfield@westbrook-district.org>',
        'Reply-To: "Dana Whitfield" <dwhitfield.admin@consultant-mail.co>',
        'To: "Tran Nguyen" <t.nguyen@westbrook-district.org>',
        'Subject: Quick favour - are you at your desk?',
        'Date: Wed, 16 Sep 2026 08:41:00 -0400',
        'Message-ID: <CAF9_2kLm8xQ@westbrook-district.org>',
        'MIME-Version: 1.0',
        'Content-Type: text/plain; charset=UTF-8',
        '',
        'Hi Tran,',
        '',
        'I am in back-to-back meetings with the board this morning and cannot take calls.',
        'I need your help with something time-sensitive for the staff appreciation event.',
        '',
        'Could you pick up eight $100 gift cards this morning? I will approve the',
        'reimbursement as soon as I am out. Please keep this confidential for now --',
        'I want it to be a surprise for the department leads.',
        '',
        'Send me photos of the codes on the back once you have them so I can forward',
        'them to the vendor immediately.',
        '',
        'Thank you, I really appreciate you handling this.',
        '',
        'Dana Whitfield',
        'Principal, Westbrook District',
        'Sent from my iPhone'
      ].join('\n')
    },

    {
      id: 'homograph',
      name: 'Homograph attack',
      blurb: 'The domain is not the domain. Reading carefully cannot save you.',
      teaches: 'Punycode · Cyrillic substitution · why "check the URL" is broken advice',
      raw: [
        'Delivered-To: you@example.com',
        'Received: from smtp.xn--microsft-secure-esm.com (smtp.xn--microsft-secure-esm.com. [192.0.2.91])',
        '        by mx.example.com with ESMTPS id 4kd93js',
        '        for <you@example.com>; Tue, 15 Sep 2026 22:04:11 -0700 (PDT)',
        'Authentication-Results: mx.example.com;',
        '       dkim=pass header.d=xn--microsft-secure-esm.com;',
        '       spf=pass smtp.mailfrom=noreply@xn--microsft-secure-esm.com;',
        '       dmarc=pass (p=NONE dis=NONE) header.from=xn--microsft-secure-esm.com',
        'Return-Path: <noreply@xn--microsft-secure-esm.com>',
        'From: "Microsoft 365 Account Team" <account-security@xn--microsft-secure-esm.com>',
        'To: you@example.com',
        'Subject: Action required: your password expires today',
        'Date: Wed, 16 Sep 2026 01:04:08 -0400',
        'Message-ID: <a91kd0@xn--microsft-secure-esm.com>',
        'MIME-Version: 1.0',
        'Content-Type: text/html; charset=UTF-8',
        '',
        '<html><body style="font-family:Segoe UI,Arial,sans-serif">',
        '<p>Your organisation requires you to update your password today.</p>',
        '<p>Users who do not update within 12 hours will lose access to mail,',
        'Teams and shared files until an administrator restores the account.</p>',
        '<p><a href="https://login.xn--microsft-secure-esm.com/common/oauth2/authorize">',
        'Keep my current password</a></p>',
        '<p>You may also sign in directly at ',
        '<a href="https://xn--netflx-tvf.com/billing/update">https://www.netflix.com/billing</a>',
        ' to review linked subscriptions.</p>',
        '<p>Microsoft respects your privacy.</p>',
        '</body></html>'
      ].join('\n')
    },

    {
      id: 'payload',
      name: 'Malware delivery',
      blurb: 'The filename you read is not the file that runs.',
      teaches: 'Double extensions · macro documents · hidden-extension blind spot',
      raw: [
        'Delivered-To: accounts@example.com',
        'Received: from mta-04.billingdocs-cloud.net (mta-04.billingdocs-cloud.net. [198.51.100.203])',
        '        by mx.example.com with ESMTP id 71ksj3',
        '        for <accounts@example.com>; Mon, 14 Sep 2026 11:22:09 -0400 (EDT)',
        'Authentication-Results: mx.example.com;',
        '       dkim=none;',
        '       spf=softfail smtp.mailfrom=billing@billingdocs-cloud.net;',
        '       dmarc=fail (p=NONE dis=NONE) header.from=northgate-supply.com',
        'Return-Path: <billing@billingdocs-cloud.net>',
        'From: "Northgate Supply Accounts" <invoices@northgate-supply.com>',
        'To: accounts@example.com',
        'Subject: Overdue invoice 8841 - remittance required',
        'Date: Mon, 14 Sep 2026 11:22:05 -0400',
        'Message-ID: <inv8841@billingdocs-cloud.net>',
        'MIME-Version: 1.0',
        'Content-Type: multipart/mixed; boundary="----=_Part_8271_193847"',
        '',
        '------=_Part_8271_193847',
        'Content-Type: text/plain; charset=UTF-8',
        '',
        'Good morning,',
        '',
        'Please find attached invoice 8841, now 46 days overdue. Our accounts team',
        'has been instructed to escalate unpaid balances to collections immediately',
        'if remittance is not confirmed today.',
        '',
        'The remittance advice must be opened and signed before payment is processed.',
        '',
        'Regards,',
        'Accounts Receivable',
        '',
        '------=_Part_8271_193847',
        'Content-Type: application/octet-stream; name="Remittance_Advice.pdf.js"',
        'Content-Transfer-Encoding: base64',
        'Content-Disposition: attachment; filename="Remittance_Advice.pdf.js"',
        '',
        'Ly8gc3ludGhldGljIHNhbXBsZSAtIG5vIHBheWxvYWQgaW4gdGhpcyBmaWxl',
        '',
        '------=_Part_8271_193847',
        'Content-Type: application/vnd.ms-word.document.macroEnabled.12; name="Invoice_8841.docm"',
        'Content-Transfer-Encoding: base64',
        'Content-Disposition: attachment; filename="Invoice_8841.docm"',
        '',
        'Lyogc3ludGhldGljIHNhbXBsZSAtIG5vIG1hY3JvIGluIHRoaXMgZmlsZSAqLw==',
        '',
        '------=_Part_8271_193847--'
      ].join('\n')
    },

    {
      id: 'genuine',
      name: 'A real one',
      blurb: 'Proof the tool can say yes. A properly authenticated notification.',
      teaches: 'What full alignment looks like · and what it still does not prove',
      raw: [
        'Delivered-To: you@example.com',
        'Received: from mail-sor-f41.google.com (mail-sor-f41.google.com. [209.85.220.41])',
        '        by mx.example.com with SMTPS id b5sor4820193pfj.62.2026.09.18.07.15.22',
        '        for <you@example.com>; Fri, 18 Sep 2026 07:15:23 -0700 (PDT)',
        'Authentication-Results: mx.example.com;',
        '       dkim=pass header.d=accounts.google.com;',
        '       spf=pass smtp.mailfrom=3xY8kQ@gaia.bounces.google.com;',
        '       dmarc=pass (p=REJECT dis=NONE) header.from=accounts.google.com',
        'DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=accounts.google.com;',
        '        s=20230601; h=to:from:subject:date:message-id; bh=8Lm2Qp9=; b=K2nd9s',
        'Return-Path: <3xY8kQ@gaia.bounces.google.com>',
        'From: "Google" <no-reply@accounts.google.com>',
        'To: you@example.com',
        'Subject: New sign-in to your Google Account on Windows',
        'Date: Fri, 18 Sep 2026 14:15:20 GMT',
        'Message-ID: <Wt3xK9Lm2@accounts.google.com>',
        'MIME-Version: 1.0',
        'Content-Type: text/html; charset=UTF-8',
        '',
        '<html><body style="font-family:Roboto,Arial,sans-serif;color:#202124">',
        '<h2>New sign-in on Windows</h2>',
        '<p>Your Google Account was just used to sign in on a Windows device.</p>',
        '<p>You are receiving this notification so you know what is happening',
        'on your account.</p>',
        '<p><a href="https://myaccount.google.com/notifications">Check activity</a></p>',
        '<p>You can also see security activity at<br>',
        '<a href="https://myaccount.google.com/notifications">https://myaccount.google.com/notifications</a></p>',
        '</body></html>'
      ].join('\n')
    },

    {
      id: 'newsletter',
      name: 'Legitimate bulk mail',
      blurb: 'The mismatch that is supposed to be there.',
      teaches: 'Why a third-party Return-Path is normal · how alignment rescues it',
      raw: [
        'Delivered-To: you@example.com',
        'Received: from mail187.sendersvc-mta.com (mail187.sendersvc-mta.com. [198.51.100.187])',
        '        by mx.example.com with ESMTPS id 92kd0s',
        '        for <you@example.com>; Thu, 17 Sep 2026 06:00:11 -0700 (PDT)',
        'Authentication-Results: mx.example.com;',
        '       dkim=pass header.d=harbourbooks.com;',
        '       spf=pass smtp.mailfrom=bounce-7281@sendersvc-mta.com;',
        '       dmarc=pass (p=QUARANTINE dis=NONE) header.from=harbourbooks.com',
        'DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=harbourbooks.com;',
        '        s=mail; h=from:subject:to; bh=2Kd9Lm=; b=9sKd02',
        'Return-Path: <bounce-7281@sendersvc-mta.com>',
        'From: "Harbour Books" <hello@harbourbooks.com>',
        'To: you@example.com',
        'Subject: Six new arrivals for autumn',
        'Date: Thu, 17 Sep 2026 09:00:08 -0400',
        'Message-ID: <c8e21.7281@sendersvc-mta.com>',
        'List-Unsubscribe: <https://sendersvc-mta.com/u/7281>, <mailto:u-7281@sendersvc-mta.com>',
        'MIME-Version: 1.0',
        'Content-Type: text/html; charset=UTF-8',
        '',
        '<html><body style="font-family:Georgia,serif;color:#2a2a2a">',
        '<h2>New this month</h2>',
        '<p>Six titles our booksellers could not stop talking about.</p>',
        '<p><a href="https://harbourbooks.com/new-arrivals">Browse the shelf</a></p>',
        '<p style="font-size:12px;color:#777">',
        '<a href="https://sendersvc-mta.com/u/7281">Unsubscribe</a></p>',
        '</body></html>'
      ].join('\n')
    }
  ];

  var API = { SAMPLES: SAMPLES };
  if (typeof module !== 'undefined' && module.exports) module.exports = API;
  root.ReturnPathSamples = API;
})(typeof globalThis !== 'undefined' ? globalThis : this);
